project/apps/TIENDA/urls.py
from django.urls import path, include
from .views import inicioTienda, categorias
from clientes.views import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from productos.views import ProductoList
from clientes.views import iniciar_sesion

urlpatterns = [
    path('', inicioTienda, name="inicioTienda"),
    path('clientes/', iniciar_sesion, name='clientes'),
    path('products/', ProductoList.as_view(), name='productos'),
    path('store/', categorias, name='categorias'),
]

project/apps/clientes/urls.py
# clientes app urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import AvatarUploadView, iniciar_sesion, registrar_usuario, about, editar_usuario, CustomLogoutView


app_name = 'clientes'

urlpatterns = [
    path('login/', iniciar_sesion, name='usuarios-login'),
    path('registrar/', registrar_usuario, name='usuarios-registrar'),
    path('about/', about, name='about'),
    path('editar/', editar_usuario, name='usuarios-editar'),
    path('logout/', CustomLogoutView.as_view(), name='usuarios-logout'),
    path('cargar_avatar/', AvatarUploadView.as_view(), name='cargar_avatar'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("TIENDA.urls")),
    path('', include('clientes.urls')),
    path('', include('productos.urls'), name='productos'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/TIENDA/models.py
from django.db import models
from productos.models import Producto


class Categoria(models.Model):
    CATEGORIAS = [
        ('partesuperior', 'Blusas y Camisas'),
        ('parteinferior', 'Pantalones y Faldas'),
        ('cuerpoentero', 'Vestidos y Enterizos'),
        ('segundapiel', 'Abrigos'),
        ('ropa de cama', 'Pijamas')
    ]

    nombre = models.CharField(max_length=50, choices=CATEGORIAS)

    def __str__(self):
        return self.nombre

project/apps/TIENDA/views.py
from django.shortcuts import render
from .models import Categoria
from django.http import HttpResponse, HttpRequest


def inicioTienda(request):
    return render(request, "TIENDA/index.html")


def categorias(request):
    categorias = Categoria.CATEGORIAS
    categorias_filas = [categorias[i:i+5] for i in range(0, len(categorias), 5)]
    return render(request, "TIENDA/store.html", {'categorias_filas': categorias_filas})

project/apps/TIENDA/templates/TIENDA/index.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Business Casual - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'TIENDA/assets/favicon.ico' %} " />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'TIENDA/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'TIENDA/css/stylesPropios.css' %}" rel="stylesheet" />
    </head>
    <body>
        {% include "TIENDA/navegacion.html" %}
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class= "Bienvenida_index" class="site-heading-upper "  >Bienvenidos a nuestra tienda</span>
                <span class="Bienvenida_index2" class="site-heading-lower" >ATHENIA</span>
            </h1>
        </header>
        <!-- <section class="page-section clearfix">
            
        </section> -->
        <section class="page-section cta">
            <div class="container">
                <div class="row">
                    <div class="col-xl-9 mx-auto">
                        <div class="cta-inner bg-faded text-center rounded">
                            <h2 class="section-heading mb-4">
                                <span class="section-heading-upper">Sobre</span>
                                <span class="section-heading-lower">Nosotros</span>
                            </h2>
                            <p class="mb-0">¡Hola! Somos Athenia, una tienda de ropa femenina que se encuentra ubicada en la ciudad de Córdoba, Argentina. Al ingresar a nuestra tienda, obtendrá un servicio amable, un ambiente acogedor y, sobre todo, excelentes productos elaborados con los mejores textiles que se encuentran en el mercado y una gran creatividad en nuestros diseños. Si no está satisfecho, háganoslo saber y haremos todo lo posible para hacer las cosas bien.</p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <section class="index_image">
            <img class=" index_image_1" src= "{% static 'TIENDA/assets/img/index_imagen.jfif' %}" />
            <img class=" index_image_2" src= "{% static 'TIENDA/assets/img/index_imagen2.jfif' %}" />
        </section>
        
        <section class="page-section about-heading">
            <div class="container">
                <div class="about-heading-content">
                    <div class="row">
                        <div class="col-xl-9 col-lg-10 mx-auto">
                            <div class="bg-faded rounded p-5">
                                <h2 class="section-heading mb-4">
                                    <span class="section-heading-upper">Welcome and Enjoy</span>
                                    <span class="section-heading-lower">About me</span>
                                </h2>
                                <p>Hola, soy Milagros Arraras la creadora de esta página web.Espero puedan visualizar mis conocimientos, faltan mejoras pero seguiré aprendiendo y mejorando!</p>
                                <p class="mb-0">
                                
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'TIENDA/js/scripts.js' %} "></script>
    </body>
</html>

project/apps/TIENDA/templates/TIENDA/navegacion.html
<nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
        <a class="navbar-brand text-uppercase fw-bold d-lg-none" href="{% url 'inicioTienda' %}">TIENDA</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'inicioTienda' %}">Home</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'categorias' %}">Categorías</a></li>
                <li class="nav-item px-lg-4"><a class="nav-link text-uppercase" href="{% url 'clientes' %}">Clientes</a></li>
                {% if request.user.is_authenticated %}
                <div class="dropdown">
                    <a class="btn btn-secondary dropdown-toggle" href="{% url 'clientes' %}" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        {%if request.user.avatar %}
                            <img style="width: 30px; height: 30px;" src="{{ request.user.avatar.imagen.url }}" alt="Avatar del usuario" class="user-avatar">
                        {% endif %}
                    </a>
                  
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'clientes:usuarios-editar' %}">Editar Usuario</a></li>
                        <li><a class="dropdown-item" href="{% url 'clientes:cargar_avatar' %}">Cargar Avatar</a></li>
                        <li><a class="dropdown-item" href="{% url 'clientes:usuarios-logout' %}">Logout</a></li>
                    </ul>
                </div>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

project/apps/TIENDA/templates/TIENDA/store.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Business Casual - Start Bootstrap Theme</title>
    <link rel="icon" type="image/x-icon" href="{% static 'TIENDA/assets/favicon.ico' %}">
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'TIENDA/css/styles.css' %}" rel="stylesheet">
    <link href="{% static 'TIENDA/css/stylesPropios.css' %}" rel="stylesheet">
</head>
<body>
    {% include "TIENDA/navegacion.html" %}
    <header>
        <h1 class="site-heading text-center text-faded d-none d-lg-block">
            <span class="Bienvenida_index2 site-heading-lower">Categoria de prendas</span>
        </h1>
    </header>
    <section class="page-section cta">
        <div class="container">
            <div class="row">
                <div class="col-xl-9 mx-auto">
                    <div class="cta-inner bg-faded text-center rounded">
                        <h2 class="section-heading mb-5">
                            
                            <span class="section-heading-upper">Estas son</span>
                            <span class="section-heading-lower">nuestras prendas</span>
                        </h2>
                        <h1 class="title__table">Categorias</h1>

                        <div style="width: 100%; margin: 0 auto;">
                            <table class="table__store">
                              {% for fila in categorias_filas %}
                                <tr>
                                  {% for categoria in fila %}
                                    <td style="padding: 10px; text-align: center;">{{ categoria.0 }}</td>
                                  {% endfor %}
                                </tr>
                                <tr>
                                  {% for categoria in fila %}
                                    <td style="padding: 10px; text-align: center;">{{ categoria.1 }}</td>
                                  {% endfor %}
                                </tr>
                              {% endfor %}
                            </table>
                        </div>

                        <a href="{% url 'productos' %}" class="button__table">
                            {% if user.is_authenticated %}
                                Ver stock de productos
                            {% else %}
                                Ver Productos
                            {% endif %}
                        </a>
                        <section>
                            <img class=" index_image_3" src= "{% static 'TIENDA/assets/img/categorias_imagen5.jfif' %}" />
                        </section>
                        

                        <p class="instagram address mb-5">
                            <em>
                                <strong> @athenia_cba </strong>
                                <br>
                                Podes seguirnos en nuestro instagram
                            </em>
                        </p>
                        <p class="mb-0">
                            <small><em>Contacto</em></small>
                            <br>
                            (317) 585-8468
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer text-faded text-center py-5">
        <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'TIENDA/js/scripts.js' %}"></script>
</body>
</html>