project/apps/productos/urls.py
from django.urls import path
from .views import ProductoList, ProductoCreate, ProductoDetail, ProductoUpdate, ProductoDelete


app_name = "productos"

urlpatterns = [
    path('', ProductoList.as_view(), name='lista_productos'),  # Lista de productos
    path('crearproducto/', ProductoCreate.as_view(), name='crear_producto'),
    path('detalleproducto/<int:pk>/', ProductoDetail.as_view(),
         name='detalle_producto'),  # Detalles del producto
    path('editarproducto/<int:pk>', ProductoUpdate.as_view(),
         name='editar_producto'),  # Editar producto
    path('eliminarproducto/<int:pk>/', ProductoDelete.as_view(),
         name='eliminar_producto'),  # Eliminar producto
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("TIENDA.urls")),
    path('', include('clientes.urls')),
    path('', include('productos.urls'), name='productos'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/productos/models.py
from django.db import models

class Producto(models.Model):
    descripcion = models.CharField(max_length=50)
    talle = models.CharField(max_length=50, default="")
    precio = models.FloatField()
    imagen = models.ImageField(upload_to='productos/', blank=True, null=True)  # Agrega este campo

    def __str__(self):
        return f"Descripción: {self.descripcion} - Talle: {self.talle} - Precio: {self.precio}"

project/apps/productos/forms.py
from django import forms
from .models import Producto

class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = '__all__'

project/apps/productos/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from .models import Producto
from .forms import ProductoForm


class ProductoList(ListView):
    model = Producto
    template_name = "productos/products.html"
    context_object_name = "productos"

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ProductoForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ProductoForm(request.POST)
        if form.is_valid():
            producto = Producto(
                descripcion=form.cleaned_data['descripcion'],
                talle=form.cleaned_data['talle'],
                precio=form.cleaned_data['precio']
            )
            producto.save()
            form = ProductoForm()
        else:
            form = ProductoForm()

        productos = self.model.objects.all()
        context = {"productos": productos, "form": form}
        return self.render_to_response(context)


@method_decorator(login_required(login_url=reverse_lazy('clientes:usuarios-login')), name='dispatch')    
class ProductoCreate(CreateView):
    model = Producto
    form_class = ProductoForm
    template_name = "productos/crearproducto.html"
    success_url = reverse_lazy("productos")



class ProductoDetail(DetailView):
    template_name = "productos/detalleproducto.html"
    model = Producto


@method_decorator(login_required(login_url=reverse_lazy('clientes:usuarios-login')), name='dispatch')
class ProductoUpdate(UpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = "productos/crearproducto.html"
    success_url = reverse_lazy("productos")


@method_decorator(login_required(login_url=reverse_lazy('clientes:usuarios-login')), name='dispatch')
class ProductoDelete(DeleteView):
    model = Producto
    template_name = "productos/eliminarproducto.html"
    success_url = reverse_lazy("productos")

project/apps/productos/templates/productos/crearproducto.html
{% extends 'productos/products.html' %}

    {% block INDEX_TITULO %} 
    <section class="section__crear__product">
        <h2>Crear/Actualizar Productos</h2>
    </section>
    {% endblock INDEX_TITULO %}




{% block INDEX_CONTENIDO %}
    
    <form class="form__crear__product" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit">Guardar</button>
    </form>

    <section class="regresar__section__product">
        <a href="{% url 'productos' %}" class="button__product">
            Regresar a productos
        </a>
    </section>
{% endblock INDEX_CONTENIDO %}

project/apps/productos/templates/productos/detalleproducto.html
{% extends 'productos/products.html' %}

{% block INDEX_TITULO %} 
    <h1 style="color:white">Detalles del Producto</h1>
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    
    <ul style="color:white">
        <li>Descripción: {{ object.descripcion }}</li>
        <li>Talle: {{ object.talle }}</li>
        <li>Precio: {{ object.precio }}</li>
    </ul>


    <a href="{% url 'productos' %}" class="btn btn-primary">
        Regresar a productos
    </a>
{% endblock INDEX_CONTENIDO %}

project/apps/productos/templates/productos/eliminarproducto.html
{% extends 'productos/products.html' %}

{% block INDEX_TITULO %} 
    
<h2 class="titulo__eliminar">Eliminar Productos</h2>
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
<section class="eliminar__producto">
    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object }}"?</p>

        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Confirmar</button>
        </form>

        <a href="{% url 'productos' %}" class="btn btn-primary">
            Regresar a productos
        </a>

</section>
   
{% endblock INDEX_CONTENIDO %}

project/apps/productos/templates/productos/listaproducto.html
{% extends 'productos/products.html' %}
AAAA
{% block INDEX_TITULO %} 
    Detalles del Producto
{% endblock INDEX_TITULO %}

{% block INDEX_CONTENIDO %}
    {% if object_list %}

        {% for object in object_list %}
            <ul>
                <li>{{ object.nombre }}
                    <a href="{% url 'productos:detalle_producto' object.id %}">Ver detalle</a>
                    <a href="{% url 'productos:crear_producto' object.id %}">Actualizar</a>
                    <a href="{% url 'productos:eliminar_producto' object.id %}">Eliminar</a>
                </li>
            </ul>
        {% endfor %}        
    {% else %}
        <p>no hay elementos</p>

    {% endif %}


    <a href="{% url 'productos' %}" class="btn btn-primary">
        Regresar a productos
    </a>
{% endblock INDEX_CONTENIDO %}

project/apps/productos/templates/productos/products.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Business Casual - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'TIENDA/assets/favicon.ico' %} " />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'TIENDA/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'TIENDA/css/stylesPropios.css' %}" rel="stylesheet" />

    </head>
    <body>
        {% include "TIENDA/navegacion.html" %}
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="Bienvenida_index site-heading-upper ">Esta es nuesta lista de</span>
                <span class="Bienvenida_index2" class="site-heading-lower">PRODUCTOS</span>
                <span class="Bienvenida_index site-heading-upper ">en stock</span>
            </h1>
        </header>
        {% block INDEX_TITULO %} 
        <!-- Deja el bloque INDEX_TITULO abierto para que pueda ser extendido en el template hijo -->
        {% endblock INDEX_TITULO %}
    
        {% block INDEX_CONTENIDO %}
        <!-- Deja el bloque INDEX_CONTENIDO abierto para que pueda ser extendido en el template hijo -->
        {% endblock INDEX_CONTENIDO %}
        {% block content %}
          <section class="Create_products">
            {% if request.user.is_authenticated %}
                <li class="list__product">

                    <button class="button__product1"><a class="products__link__a2" href="{% url 'productos:crear_producto' %}">Crear Productos</a> </button>
                </li>
            {% endif %}
          </section>  
            
          <div class="row">
            {% for producto in productos %}
            <div class="col-md-4 mb-4">
                <div class="card" style="width: 18rem;">
                    {% if producto.imagen %}
                        <img src="{{producto.imagen.url}}" class="card-img-top" alt="{{ producto.descripcion }}">
                    {% endif %}    
                    <div class="card-body"> 
                        <h5 class="card-title">{{ producto.descripcion }}</h5>
                        <p class="card-text">{{ producto.talle }}</p>
                        <p class="card-text">${{ producto.precio }}</p>
                    </div>
                    {% if request.user.is_authenticated %}
                    <div class="card-footer">
                        <a href="{% url 'productos:detalle_producto' producto.pk %}" class="card-link">Ver detalle</a>
                        <a href="{% url 'productos:editar_producto' producto.pk %}" class="card-link">Actualizar</a>
                        <a href="{% url 'productos:eliminar_producto' producto.pk %}" class="card-link">Eliminar</a>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>        
     {% endblock %}


        <section class="page-section">
            <div class="container">
                <div class="product-item">
                    <div class="product-item-title d-flex">
                        <div class="bg-faded p-5 d-flex ms-auto rounded">
                            <h2 class="section-heading mb-0">
                                <span class="section-heading-upper">Seccion exclusiva para vendedores</span>
                                <span class="section-heading-lower">Nuestros productos</span>
                            </h2>
                        </div>
                    </div>
                    <div class="product-item-description d-flex me-auto">
                        <div class="bg-faded p-5 rounded"><p class="mb-0">Si eres uno de nuestros vendedores podras subir que productos tenemos disponibles iniciando sesión en la sesión de clientes.Estos tendrán su respectivo talle y precio según stock en tienda.</p></div>
                    </div>
                </div>
            </div>
        </section>
        <section class="page-section">
            <div class="container">
                <div class="product-item">
                    <div class="product-item-title d-flex">
                        <div class="bg-faded p-5 d-flex me-auto rounded">
                            <h2 class="section-heading mb-0">
                                <span class="section-heading-upper">Pasos a</span>
                                <span class="section-heading-lower">seguir</span>
                            </h2>
                        </div>
                    </div>
                    <div class="product-item-description d-flex ms-auto">
                        <div class="bg-faded p-5 rounded"><p class="mb-0">Deberás cargar en descripción la tipología de prenda ejemplo; falda, pantalón, vestido, etc. Luego en talles deberás poner las siguientes opciones; xs, s, m, l ,xl, xxl, xxl. Por último su precio acorde al producto!.</p></div>
                    </div>
                </div>
            </div>
 
        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'TIENDA/js/scripts.js' %} "></script>
    </body>
</html>