project/apps/clientes/urls.py
# clientes app urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import AvatarUploadView, iniciar_sesion, registrar_usuario, about, editar_usuario, CustomLogoutView


app_name = 'clientes'

urlpatterns = [
    path('login/', iniciar_sesion, name='usuarios-login'),
    path('registrar/', registrar_usuario, name='usuarios-registrar'),
    path('about/', about, name='about'),
    path('editar/', editar_usuario, name='usuarios-editar'),
    path('logout/', CustomLogoutView.as_view(), name='usuarios-logout'),
    path('cargar_avatar/', AvatarUploadView.as_view(), name='cargar_avatar'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("TIENDA.urls")),
    path('', include('clientes.urls')),
    path('', include('productos.urls'), name='productos'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/apps/clientes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Group, Permission
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from productos.models import Producto

class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=30, verbose_name=_('First name'))
    last_name = models.CharField(max_length=30, verbose_name=_('Last name'))
    email = models.EmailField(unique=True, verbose_name=_('Email'))
    is_active = models.BooleanField(default=True, verbose_name=_('Active'))
    date_joined = models.DateTimeField(auto_now_add=True, verbose_name=_('Date joined'))

    custom_groups = models.ManyToManyField(Group, related_name='custom_users', blank=True, verbose_name=_('groups'))
    custom_user_permissions = models.ManyToManyField(Permission, related_name='custom_users', blank=True, verbose_name=_('user permissions'))

    def __str__(self):
        return self.username

class Avatar(models.Model):
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    imagen = models.ImageField(
    upload_to='avatares', null=True, blank=True, default="/default.jpeg")

class Mensajes(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    articulo = models.ForeignKey(Producto, on_delete=models.CASCADE)
    mensaje = models.CharField(max_length=300)
    fecha = models.DateTimeField(auto_now=True)

project/apps/clientes/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django.utils.translation import gettext_lazy as _

class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(label=_("Nombre"))
    last_name = forms.CharField(label=_("Apellido"))
    email = forms.EmailField(label=_("Correo electrónico"))
    password1 = forms.CharField(label=_("Contraseña"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Confirme contraseña"), widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]
        help_texts = { "email": _("Indica un correo electrónico que uses habitualmente"), "first_name": "", "last_name": "", "password1": ""}


class UserEditForm(UserChangeForm):
    first_name = forms.CharField(label=_("Nombre"))
    last_name = forms.CharField(label=_("Apellido"))
    email = forms.EmailField(label=_("Correo electrónico"))
    password1 = forms.CharField(label=_("Contraseña"), widget=forms.PasswordInput, required=False)
    password2 = forms.CharField(label=_("Confirme contraseña"), widget=forms.PasswordInput, required=False)

    class Meta:
        model = CustomUser
        fields = ["first_name", "last_name", "email", "password1", "password2"]
        help_texts = { "email": _("Indica un correo electrónico que uses habitualmente"), "first_name": "", "last_name": ""}

project/apps/clientes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate 
from django.contrib.auth.forms import AuthenticationForm
from django.views import View
from clientes.forms import UserRegisterForm, UserEditForm
from clientes.models import *
from django.contrib.auth.decorators import login_required
from productos import *
from django.http import HttpResponseServerError
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from django.utils import timezone
# importo el paquete os para manejar nombres de archivo
import os

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


def iniciar_sesion(request):
    errors = ""

    if request.method == "POST":
        formulario = AuthenticationForm(request, data=request.POST)

        if formulario.is_valid():
            data = formulario.cleaned_data
            user = authenticate(username=data["username"], password=data["password"])

            if user is not None:
                login(request, user)
                return redirect("productos:lista_productos")  # Redirigir a la página de inicio de la TIENDA
            else:
                return render(request, "clientes/login.html", {"form": formulario, "errors": "Credenciales no válidas"})
        else:
            return render(request, "clientes/login.html", {"form": formulario, "errors": formulario.errors})

    formulario = AuthenticationForm()
    return render(request, "clientes/login.html", {"form": formulario, "errors": errors})

def registrar_usuario(request):
    errors = ""
    if request.method == "POST":
        formulario = UserRegisterForm(request.POST)
        if formulario.is_valid():
            data = formulario.cleaned_data
            formulario.save()
            user = authenticate(username=data["username"], password=data["password1"])
            login(request, user)
            return redirect("productos:lista_productos")
        else:
            return render(request, "clientes/registrar_usuario.html", {"form": formulario, "errors": errors})

    formulario = UserRegisterForm()
    return render(request, "clientes/registrar_usuario.html", {"form": formulario, "errors": errors})


@login_required
def about(request):
    usuarios = usuarios.objects.all() 
    context = {"usuarios": usuarios}
    return render(request, "clientes/about.html", context)



@login_required(login_url=reverse_lazy('clientes:usuarios-login')) 
def editar_usuario(request):
    usuario = request.user
    if request.method == "POST":
        formulario = UserEditForm(request.POST, instance=usuario)

        if formulario.is_valid():
            data = formulario.cleaned_data
            usuario.first_name = data["first_name"]
            usuario.last_name = data["last_name"]
            usuario.email = data["email"]
            if data["password1"]:  # Verifica si se proporcionó una nueva contraseña
                usuario.set_password(data["password1"])
            usuario.save()
            messages.success(request, 'Cambios guardados exitosamente.')
            return redirect("clientes")
        else:
            messages.error(request, 'Error al guardar los cambios. Por favor, corrige los errores.')

    else:
        formulario = UserEditForm(instance=usuario)

    return render(request, "clientes/editar_usuario.html", {"form": formulario, "usuario": usuario})




@method_decorator(login_required(login_url=reverse_lazy('clientes:usuarios-login')), name='dispatch')
class AvatarUploadView(View):
    template_name = 'clientes/avatar_upload.html'

    def get(self, request):
        user = request.user
        avatar, created = Avatar.objects.get_or_create(user=user)
        return render(request, self.template_name, {'avatar': avatar})
    
    def post(self, request):
        user = request.user
        avatar, created = Avatar.objects.get_or_create(user=user)

        try:
            if 'imagen' in request.FILES:
                avatar.imagen = request.FILES['imagen']
                avatar.save()
                messages.success(request, 'Avatar cargado exitosamente.')
                return redirect('cargar_avatar')
        except Exception as e:
            messages.error(request, f'Error al cargar el avatar: {str(e)}')

        return render(request, self.template_name, {'avatar': avatar})


def avatar_usuario(usuario_activo):
    if usuario_activo.is_authenticated:
        if Avatar.objects.filter(user=usuario_activo.id).exists():
            imagen_model = Avatar.objects.get(user=usuario_activo.id)
            imagen_url = imagen_model.imagen.url
        else:
            imagen_url = ""
    else:
        imagen_url = ""
    return imagen_url

@login_required(login_url=reverse_lazy('clientes:usuarios-login'))
def mostrar_navbar(request):
    usuario_activo = request.user
    avatar_url = avatar_usuario(usuario_activo)

    context = {
        'avatar_url': avatar_url
    }
    return render(request, 'clientes/navbar.html', context)



class CustomLogoutView(LogoutView):
    template_name = 'clientes/logout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        logout_time = timezone.now().strftime("%Y-%m-%d %H:%M:%S")
        context['logout_time'] = logout_time
        return context

project/apps/clientes/templates/clientes/about.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Business Casual - Start Bootstrap Theme</title>
        <link rel="icon" type="image/x-icon" href="{% static 'TIENDA/assets/favicon.ico' %} " />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'TIENDA/css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'TIENDA/css/stylesPropios.css' %}" rel="stylesheet" />

    </head>
    <body>
        {% include "TIENDA/navegacion.html" %}
        <header>
            <h1 class="site-heading text-center text-faded d-none d-lg-block">
                <span class="Bienvenida_index site-heading-upper ">Bienvenido a nuestra sección</span>
                <span class="Bienvenida_index2 site-heading-lower"> Clientes</span>
            </h1>
        </header>
        {% block contenido %}
        
        {% endblock %}

        <footer class="footer text-faded text-center py-5">
            <div class="container"><p class="m-0 small">Copyright &copy; Your Website 2023</p></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'TIENDA/js/scripts.js' %} "></script>
    </body>
</html>

project/apps/clientes/templates/clientes/avatar_upload.html
{% extends 'clientes/about.html' %}

{% block contenido %}

<h1 class=" upload_avatar mt-4"> Cargar avatar </h1>
<section class="section__avatar">


<!-- {% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %} -->

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="imagen" accept="image/*" required>
    <button type="submit">Cargar</button>
</form>

{% if avatar.imagen %}
    <h3>Avatar actual:</h3>
    <img src="{{ avatar.imagen.url }}" alt="Avatar">

</section>
{% endif %}
{% endblock %}

project/apps/clientes/templates/clientes/editar_usuario.html
{% extends 'clientes/about.html' %}

{% block contenido %}

<h1 class="user__title"> Modificar datos de usuario </h1>
<section class="editar__usuario__section">

{% if errors %}
    <p>Errores registro de usuario: {{errors}}</p>
{% endif %}

<form method="post">
    {% csrf_token %}

    <div class="form-group">
        <label for="{{ form.first_name.id_for_label }}">Nombre</label>
        {{ form.first_name }}
    </div>

    <div class="form-group">
        <label for="{{ form.last_name.id_for_label }}">Apellido</label>
        {{ form.last_name }}
    </div>

    <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Correo electrónico</label>
        {{ form.email }}
    </div>

    <div class="form-group">
        <label for="{{ form.password1.id_for_label }}">Contraseña</label>
        {{ form.password1 }}
    </div>

    <div class="form-group">
        <label for="{{ form.password2.id_for_label }}">Confirme contraseña</label>
        {{ form.password2 }}
    </div>

    <input type="submit" value="Guardar Modificaciones">
</form>
</section>

{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

{% endblock %}

project/apps/clientes/templates/clientes/login.html
{% extends 'clientes/about.html' %}

{% block contenido %}
<section class="login_section">
    <h1 class="mt-4"> Inicio de sesión </h1>
</section>


{% if errors %}
    <p>Errores en inicio de sesión: {{ errors }}</p>
{% endif %}

<section class="login_section">
    <form class="login_form" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Iniciar sesión">
    </form>
</section>
    
<section class="login_section">
    <p class="login_texto"> No estás registrado?    <button class="login_button"><a class="login__a" href="{% url 'clientes:usuarios-registrar' %}"> Registrate! </a></p></button>

</section>

{% endblock %}

project/apps/clientes/templates/clientes/logout.html
{% extends 'clientes/about.html' %}
{% load static %}


{% block contenido %}
<section class="logout__message">
    <h2 class="logout__titulo"> Tu sesión ha cerrado </h2>
    
    <p class="logout__parrafo"> Cerraste sesión el {{ logout_time }}. </p>
    <img class="logout__image" src= "{% static 'TIENDA/assets/img/logout_img2.jfif' %}" />

</section>
{% endblock %}

project/apps/clientes/templates/clientes/registrar_usuario.html
{% extends 'clientes/about.html' %}

{% block contenido %}

<h1 class=" titulo__registrar mt-4"> Registrar nuevo usuario </h1>

<section class="section__registrar__usuario">
    

        {% if errors %}
            <p>Errores registro de usuario: {{errors}}</p>
        {% endif %}

    <form method="post">
        {% csrf_token %}

        {{form.as_p}}

        <input type="submit" value="Registrar Usuario">
    </form>
    <p> </p>
    

</section>
<p class="titulo__registrar1"> ¿Ya tenés una cuenta? <button class="login_button"><a class="login__a" href="{% url 'clientes:usuarios-login' %}"> Iniciá sesión </a></button></p>

{% endblock %}